### ISSUE TITLE
More changes to broadcast or commands?

### ISSUE THREAD

**Issue by akameswaran** [greghesp/assistant-relay#37] opened 2018-07-01 20:54 UTC
I will admit I am new to this, but it seems as though my google home ignores everything.

I have setup the assistant relay and have been using curl to run the commands.  When i view my activity in Google Home App, I see the assistant showing up and the commands, but nothing happens.

So if I use customBroadcast?text=blah&user=me&converse=true  I do see a broadcast request in my activity but the Google Home speaker does nothing.  If I type it into Google Assistant app on my phone she does speak.

Similarly 
custom?Command="Play+some+band+it+recognizes"
gets me I don't know how to help with that message from Assistant relay, meanwhile speaking the same words Google responds.

So is this an issue with Google?  Or is it possible something on my setup is wrong.
FWIW, when I setup the node.js server Google Home never acknowledged it.

**Comment by akameswaran** [comment] 2018-07-01 21:44
And one more.

Just for fun I set this up on a spare rPi 3 I had lying around.  Same issue.

During first run I do get this odd error:
Paste your code: (node:13552) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Exited with code 3

However, it does not stop the server from running if the right credentials.json is in place and I copy/paste properly.

**Comment by ryancasler** [comment] 2018-07-02 00:55
I just created a new project today and it worked just like the instructions on my page.  The device you're creating isn't "other" that's the credential type you have to create.
http://github.com/ryancasler/assistant-relay/wiki

**Comment by do1eh** [comment] 2018-07-02 07:52
@ryancasler so that sounds like got it working again? Does creating a new project on google help? Or should I just reinstall the relay?

**Comment by akameswaran** [comment] 2018-07-02 14:48
So I wiped out node.js and reinstalled 9.9.0.  I also created a new project and client ID via the wiki instructions instead of readme.md version (FWIW - Following those instructions and creating a device, does end up creating an OAUTH client ID with type other)

When launching for the first time I got a more verbose error:
Paste your code: (node:17282) UnhandledPromiseRejectionWarning: Error: Exited with code 3
    at ChildProcess.cp.once.code (/home/pi/tmp/assistant-relay-master/node_modules/opn/index.js:84:13)
    at Object.onceWrapper (events.js:272:13)
    at ChildProcess.emit (events.js:180:13)
    at maybeClose (internal/child_process.js:936:16)
    at Socket.stream.socket.on (internal/child_process.js:353:11)
    at Socket.emit (events.js:180:13)
    at Pipe._handle.close [as _onclose] (net.js:541:12)
(node:17282) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:17282) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

However, I did get a link, and I was able to login and copy and paste the token.  The only drift from the instructions is that I do not have X installed on my pi's - and I used copy and paste in Konsole.  I don't believe that is causing any issue, as during an earlier attempt I did make a mistake and the server crashes with errors when a mistake is made.

At this point, I have the same results - google home app shows the activity coming in but I can't get the google home speaker to say anything regardless of converse=true.  I also did some little tweaks in the code etc, and while I didn't read all of it - I can confirm that the converse option is making it under the right API end points (ie adding console.log("Passed returnAudio Check")  kind of stuff.

Once I am passed the initial user setup there are no visible errors.  Are there logs or something else I could check?

**Comment by ryancasler** [comment] 2018-07-04 18:01
No.  I'm still unable to get Relay working correctly.  It seems to be a Google issue because I'm not the only having the problem.  I went back to start and it still didn't work.

**Comment by naseemr** [comment] 2018-07-08 22:07
I am having the same problem,  shows on activity but no broadcast on google home

**Comment by do1eh** [comment] 2018-07-09 06:21
No. At the moment you can do nothing because the problem is on googles side.

**Comment by red3recon** [comment] 2018-07-09 13:41
To be sure, not everyone is having the broadcast problem are they? Mine is
working where it announces what I put in webcore "Front door open" for
example.

**Comment by do1eh** [comment] 2018-07-10 05:55
@red3recon That's correct. Some users don't have any problems at all. Right now nobody has a clue what the problem is. For sure is that this has something to do with the way google tries to find out if all devices are on the same network. Maybe you can help by describing your network setup so we can determine what the differences between our networks are.  BTW: The main thread where the problem is discussed here: [](https://github.com/endoplasmic/google-assistant/issues/52)

**Comment by red3recon** [comment] 2018-07-10 13:30
I am only a user, no real coding experience and my Linux skills are awful so please be patient with me. That said, I followed the instructions a few months ago and set this up. I have a Ubuntu server (16 LTS) where I installed the Node JS, copied my secret file and ran "node index.js" and when I do that my GH devices (3 of them all on the same subnet 10.0.0.0/24 and same wireless SSID) announce that they are online.  The part of the relay that is in the ST app did not work for me because I use Untangle as my router and it does not support the protocol that the app relies on for discovery. I added the device manually which points to my Node.JS by IP also in that same subnet and then I use webcore to put in the text that I want spoken with specific actions.  If you want me to provide any version numbers or anything you will need to spell out where you need me to look. FYI, I have not updated the relay since I got this working months ago.

**Comment by Harel-M** [comment] 2018-08-02 19:59
I'm not sure if it is still relevant, but I installed the rely today for the first time (just as the Wiki installation instructions) and it is working for me...

**Comment by greghesp** [comment] 2018-08-15 08:38
Closing as believe issue is resolved

**Closed by greghesp** 2018-08-15 08:38 UTC
