### ISSUE TITLE
Language option is not honored. Only uses US english.

### ISSUE THREAD

**Issue by thepapamaan** [greghesp/assistant-relay#178] opened 2020-05-15 15:09 UTC
**Describe the bug**
No matter which language I select in the configuration it is playing the messages in US english only. Double checked the config.json and it updates from the changes on the configuration tab in the ui. I have also rebooted after changing language. Same issue with stable and two beta versions.

**Expected behavior**
If I set Australian english then the broadcasted messages should be played back in Australian English.

**Screenshots**

**Setup:**
-  Docker apipa169/assistant-relay:beta  (v3.3.1b)
-  Docker apipa169/assistant-relay:3.3.2b
-  Docker apipa169/assistant-relay:latest  (v3.2.0)

**Additional context**

**Comment by ryancasler** [comment] 2020-05-15 23:31
This is happening with a docker container?  Is the container set to have write privileges to the config directory that it is using?  Because the option works when installed in the host OS.

**Comment by greghesp** [comment] 2020-05-19 19:19
I believe the messages are played back in the language the devices are set to.  The language passed via Assistant Relay is only the conversed language with the SDK.

For example, if your Google Home is set to US English but AR set to UK English and you ask it to broadcast "Aluminium is a metal", then it'll be spoken as "Al-um-in-um is a metal"

**Comment by greghesp** [comment] 2020-05-30 10:56
Are you able to confirm?  I've just tested this myself, and AR is honouring the language.  You can test this my changing the language in AR between `en-US` and `en-GB`, then asking it a joke and listening to the audio file.

**Comment by 6uhrmittag** [comment] 2020-06-21 13:17
> I believe the messages are played back in the language the devices are set to.

Yes, same for me. My devices/Google Assistant are set to German(+Engl. as 2. language) - The reply's text is Englisch/German depending on the command I send, but the voice used is always the German one.

Changing the GoogleAsssistant's voice is only available in US, which is probably the cause of the different experiences: https://support.google.com/googlenest/answer/7550431

**Comment by greghesp** [comment] 2020-07-13 18:14
I'm closing this as I don't believe it to be an issue with AR

**Closed by greghesp** 2020-07-13 18:14 UTC
