### ISSUE TITLE
Send custom command results in wrong user broadcast

### ISSUE THREAD

**Issue by irwan-github** [greghesp/assistant-relay#85] opened 2019-03-27 04:28 UTC
Hi

When I issue a custom command like the following:

curl -d '{"command":"Tell me a joke", "user":"john", "converse":"true"}' -H "Content-Type: application/json" -X POST http://hassbian.local:8247/assistant

**Expectation:**
The Google Home says: 
"Received command broadcast for John. Here's a joke:
What’s Forrest Gump’s password?
1forrest1

**Actual:**
The Google Home says: 
"Received command broadcast for Bob. Here's a joke:
What’s Forrest Gump’s password?
1forrest1

**Summary:**
Assistant relay is telling Google Home to make broadcast for "Bob" when the right thing is to tell Google Home to make broadcast for "John".

**Here's a sample of the log file:**

Received command Tell me a joke 

User specified was John 

Google Assistant: One joke, coming up
How did the vacuum cleaner die?
It bit the dust 💨 

Received command broadcast One joke, coming up
How did the vacuum cleaner die?
It bit the dust 💨 

No user specified, using Bob 

Conversation Complete 

Conversation Complete

**Comment by louis-lau** [comment] 2019-04-01 22:16
Not sure if you misheard, but my Google Home says "broadcast **from** $user". So in this case John would be correct. Because assistant-relay executes the broadcast as the user "john".

**Comment by irwan-github** [comment] 2019-04-01 23:23
> Not sure if you misheard, but my Google Home says "broadcast from $user". So in this case John would be correct. Because assistant-relay executes the broadcast as the user "john".

I did NOT mishear. Google Assistant executes the command as user John but it broadcast the result as user Bob. The log file suggest that when it wanted to broadcast the result of the command, it cannot detect or 'forgets' that user is John. So it used a default user that I think is based on the last user that signed in when it's service was starting.

**Comment by cgmckeever** [comment] 2019-04-30 11:07
@irwan-github you've given permissions via the google/auth/web screen to all the users? The instructions are a bit vague, I haven't actually tried with multiple users yet .. I just made a random user called Papa Smurf -- makes me laugh ;)

**Comment by greghesp** [comment] 2019-10-20 21:29
I can see what the issue is here.  

When you're setting converse to true, it passes the user john which works fine.  Since converse is set to true, it then tells Assistant Relay to broadcast the response, at which point, it does not pass a user.  Hence why you're seeing it select the default user Bob.

The issue is here: https://github.com/greghesp/assistant-relay/blob/master/server/assistant.js#L112

Will try and fix for version 3

**Comment by greghesp** [comment] 2019-10-25 14:23
Fixed in v3

**Closed by greghesp** 2019-10-25 14:23 UTC
Labels: bug
