### ISSUE TITLE
IPv6

### ISSUE THREAD

**Issue by tenoriojuann** [greghesp/assistant-relay#90] opened 2019-05-18 22:19 UTC
Can you add documentation with the issues regarding IPv6? I just ran into this issue and found out about it until I read the closed issues.

or maybe I missed it?

**Comment by yusefasjana** [comment] 2019-08-19 21:19
Could there be a fix where we don't have to disable ipv6?

**Comment by ryancasler** [comment] 2019-08-25 01:53
The issue is with the Assistant SDK, not with Assistant Relay.  It is not able to discover the devices on the network so it cannot broadcast to them.  The issue would have be resolved by Google.
https://github.com/endoplasmic/google-assistant/issues/52

**Comment by greghesp** [comment] 2019-10-20 21:23
As @ryancasler comment.  This is a Google issue unfortunately

**Closed by greghesp** 2019-10-20 21:23 UTC
Labels: not applicable

**Comment by fcastilloec** [comment] 2020-01-20 02:07
Can somebody put a note on the README? We know it's not this module fault, it's Google. Nonetheless, when people attempt to use this module and can't, it'll save everybody's time if this is mentioned somewhere besides closed issues.

**Comment by fk128** [comment] 2020-10-24 15:44
It's still possible to get it to work if the router doesn't allow disabling IPv6 but has an option for blocking traffic by IP address. By blocking all traffic to only the IPv6 addresses of the devices and restarting the router, the broadcast started working for me.

**Comment by Toukassay** [comment] 2020-10-28 22:31
> It's still possible to get it to work if the router doesn't allow disabling IPv6 but has an option for blocking traffic by IP address. By blocking all traffic to only the IPv6 addresses of the devices and restarting the router, the broadcast started working for me.

Interesting. Can you explain a bit more ? Maybe screenshots ?

**Comment by nvx** [comment] 2021-03-01 12:53
https://developers.google.com/assistant/sdk/guides/library/troubleshooting#broadcast_issues describes the behaviour in this issue:

```
Broadcast issues
The Assistant cannot broadcast messages from one device to the other.

Make sure to set the device location in the Google Assistant app. Both devices must have the same address in the app.
```

Going deeper down the rabbit hole, it looks like it is possible to send a DeviceLocation (https://developers.google.com/assistant/sdk/reference/rpc/google.assistant.embedded.v1alpha2#devicelocation) which contains coordinates in a DialogStateIn message which is a part of the AssistConfig message (the AssistConfig message is where the text_query string is which is set here https://github.com/greghesp/assistant-relay/blob/1b248f30b1be48ce30643e379b9d23d25b3f1f5c/relay/helpers/assistant.js#L14).

The description on that DeviceLocation message is as follows:

```
1. This DeviceLocation, which is primarily used for mobile devices with GPS .
2. Location specified by the user during device setup; this is per-user, per device. This location is used if DeviceLocation is not specified.
3. Inferred location based on IP address. This is used only if neither of the above are specified.
```

It sounds like option 3 is happening, since neither 1 nor 2 is fulfilled. I imagine if we populated as DeviceLocation that matches what the Google Home devices have this would prevent it using IP address to infer the location and avoid the issue.

**Comment by nvx** [comment] 2021-03-01 13:10
I suspect the other way is to register the device with https://developers.google.com/assistant/sdk/reference/device-registration/register-device-manual then have an option to provide the `deviceModelId` and `deviceId` fields instead. https://github.com/endoplasmic/google-assistant/blob/1f0b5be77cd471f782826a314b150cc54396b8e3/README.md documents this and also gives an example that includes setting the Device Location.

Registering a device might be better than setting a DeviceLocation as I'm not sure how "close" it would have to be to the lat/lng geocoding in the Google Home app, but if it's a registered device I imagine it'll just show up in the Google Home app and you can set the location there exactly the same as other Google Home devices? I'm not 100% clear on how that side works.

**Comment by ryancasler** [comment] 2021-03-04 05:01
I'm sure Greg would welcome a pull request implementing the changes you have requested.  Otherwise, it is working fine for the rest of us.  You might just have to suck it up and take it the way it is.
